Servidor/Servidor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculadora_sellos.urls')),
]

Servidor/calculadora_sellos/urls.py
from django.urls import path
from .import views

app_name = 'calculadora_sellos'

urlpatterns = [
    path("",views.index, name ='index'),
    path('recursos_externos/', views.recursos_externos, name='recursos_externos'),
    path('sobre_pagina/', views.sobre_pagina, name='sobre_pagina'),
    path('preguntas_frecuentes/', views.preguntas_frecuentes, name='preguntas_frecuentes'),
    path('contacto/', views.envio_mensaje, name='contacto'),
    path('ingreso_usuario/', views.ingreso_usuario, name= 'ingreso_usuario'),
    path("lista_recetas",views.lista_recetas, name = 'lista'),
    path('<int:id>/',views.detalle_receta, name = 'detalle_receta'),
    path("<int:id>/editar",views.editar_receta, name = 'editar'),
    path('cerrar_sesion/',views.cerrar_sesion),
    path('registro', views.registro, name='registro'),
    path('resultado', views.resultado),
    path('<int:id>/eliminar',views.eliminar_receta),
    path("crear_receta",views.crear_receta, name = 'crear'),


]

Servidor/calculadora_sellos/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.conf import settings
from django.urls import reverse


CHOICES=[('Usuario','Usuario'),
         ('Pyme','Pyme')]

class Usuario(models.Model):
    user_name = models.CharField(max_length= 50)
    email_address = models.CharField(max_length= 30)
    password = models.CharField(max_length= 12)
    nombre_grupo_usuario = models.CharField(max_length=20, choices=CHOICES)
    last_login = models.CharField(max_length= 300)


class Receta(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=CASCADE)
    nombre_receta = models.CharField(max_length= 30)
    porcion = models.FloatField()
    fecha = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("calculadora_sellos:detalle_receta", kwargs={"id":self.id})
    
    def get_editar_url(self):
        return reverse("calculadora_sellos:editar", kwargs={"id":self.id})

    def get_ingrediente_hijos(self):
        return self.ingrediente_set.all()

class Ingrediente(models.Model):
    receta = models.ForeignKey(Receta, on_delete=CASCADE)
    nombre_ingrediente = models.CharField(max_length= 30)
    cantidad = models.FloatField()
    calorias = models.FloatField()
    azucares = models.FloatField()
    sodio = models.FloatField()
    grasas = models.FloatField()

    totalCalorias = models.FloatField()
    totalAzucares = models.FloatField()
    totalSodio = models.FloatField()
    totalGrasas= models.FloatField()

    def calculate_total(self):
        return self.calorias*self.cantidad/100

    def calculate_total2(self):
        return self.azucares*self.cantidad/100
    
    def calculate_total3(self):
        return self.sodio*self.cantidad/100
    
    def calculate_total4(self):
        return self.grasas*self.cantidad/100
          
    def save(self, *args, **kwargs):
        self.totalCalorias=self.calculate_total()
        self.totalAzucares=self.calculate_total2()
        self.totalSodio=self.calculate_total3()
        self.totalGrasas=self.calculate_total4()
        super().save(*args, **kwargs)


    # def azucaresIngrediente(self):
    #     return self.azucares*self.cantidad/100

    # def save_azucares(self, *args, **kwargs):
    #     self.totalAzucares=self.azucaresIngrediente()
    #     super().save(*args, **kwargs)


 
    def get_absolute_url(self):
        return reverse("calculadora_nutricional:detalle", kwargs={"id":self.id})

 
class Contacto(models.Model):
    nombre = models.CharField(max_length= 50)
    apellido = models.CharField(max_length= 50)
    email = models.CharField(max_length= 30)
    mensaje = models.TextField(max_length= 600)

Servidor/calculadora_sellos/forms.py
from django import forms
from .models import Receta, Ingrediente, Contacto, Usuario


class UsuariosForm(forms.ModelForm):
   class Meta:
        model = Usuario
        fields = ('user_name','email_address', 'password', 'nombre_grupo_usuario')

class RecetaForm(forms.ModelForm):
    class Meta:
        model = Receta
        fields = ('nombre_receta', 'porcion')

class IngredienteForm(forms.ModelForm):
    class Meta:
        model = Ingrediente
        fields = ('nombre_ingrediente', 'cantidad', 'calorias', 'azucares', 'sodio', 'grasas')

class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ('nombre','apellido','email', 'mensaje')

Servidor/calculadora_sellos/views.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect, get_object_or_404
from .models import Receta, Ingrediente
from.forms import RecetaForm, IngredienteForm, ContactoForm, UsuariosForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout
from django.forms.models import modelformset_factory
from django.contrib.auth.models import User, Group
from django.db.models import Avg, Max, Min, Sum



def index(request):
    return render(request,'calculadora_sellos/index.html')

def resultado(request):
    return render(request,'calculadora_sellos/resultado.html')

def recursos_externos(request):
    return render(request,'calculadora_sellos/recursos_externos.html')

def sobre_pagina(request):
    return render(request,'calculadora_sellos/sobre_pagina.html')

def preguntas_frecuentes(request):
    return render(request,'calculadora_sellos/preguntas_frecuentes.html')

def registro(request):
    if request.method == "POST":
        form=UsuariosForm(data=request.POST)
        if form.is_valid():
            user_name = form.cleaned_data["user_name"]
            email_address = form.cleaned_data["email_address"]
            password=form.cleaned_data["password"]
            usuario = form.save(commit = False)
            usuario.save()
            
            user_group = User.objects.create_user(user_name, email_address,password)
            user_group.save()
            
            grupo = Group.objects.get(name=request.POST.get("nombre_grupo_usuario"))
            user_group.groups.add(grupo)
            return redirect('/ingreso_usuario')
    else:
        form = UsuariosForm()
        return render(request,'calculadora_sellos/registro_usuario.html',{'form': form})


def ingreso_usuario(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data =request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
        return redirect('/lista_recetas')
    else:
        form = AuthenticationForm()
        return render(request,'calculadora_sellos/ingreso_usuario.html', {"form":form})


@login_required(login_url = '/')
def lista_recetas(request, id=None):
    qs = Receta.objects.filter(usuario=request.user)
    context = {
        "lista":qs
    }
    return render(request, 'calculadora_sellos/lista_recetas.html', context)

    
@login_required(login_url = '/')
def detalle_receta(request, id=None):
    objeto = get_object_or_404(Receta, id=id, usuario=request.user)

    suma_cantidad = Ingrediente.objects.values('receta_id').annotate(Sum('cantidad'))
    suma_calorias = Ingrediente.objects.values('receta_id').annotate(Sum('totalCalorias'))
    suma_azucares = Ingrediente.objects.values('receta_id').annotate(Sum('totalAzucares'))
    suma_grasas = Ingrediente.objects.values('receta_id').annotate(Sum('totalGrasas'))
    suma_sodio = Ingrediente.objects.values('receta_id').annotate(Sum('totalSodio'))
        
    cantidad =([d["cantidad__sum"] for d in suma_cantidad if "cantidad__sum" in d][0])

    valor_cal =([d["totalCalorias__sum"] for d in suma_calorias if "totalCalorias__sum" in d][0])
    total_calorias = valor_cal*100/cantidad

    valor_azu =([d["totalAzucares__sum"] for d in suma_azucares if "totalAzucares__sum" in d][0])
    total_azucares = valor_azu*100/cantidad

    valor_gra =([d["totalGrasas__sum"] for d in suma_grasas if "totalGrasas__sum" in d][0])
    total_grasas = valor_gra*100/cantidad

    valor_so =([d["totalSodio__sum"] for d in suma_sodio if "totalSodio__sum" in d][0])
    total_sodio = valor_so*100/cantidad

    print(suma_grasas)

    
    context = {
        "detalle":objeto,
        "total_calorias": total_calorias,
        "total_azucares": total_azucares,
        "total_grasas": total_grasas,
        "total_sodio": total_sodio,

    }

    return render(request, 'calculadora_sellos/detalle_recetas.html', context)
  
@login_required(login_url = '/')
def crear_receta(request):
    form = RecetaForm(request.POST or None)
    ingredienteFormset= modelformset_factory(Ingrediente, form = IngredienteForm, extra = 0)
    formset = ingredienteFormset(request.POST or None)

    context = {
        "form":form,
        "formset":formset
    }
    if all([form.is_valid(), formset.is_valid()]):
        obj = form.save(commit=False)
        obj.usuario = request.user
        obj.save()
        for form in formset:
            child = form.save(commit = False)
            child.receta = obj
            child.save()
        formset.save()
        return redirect(obj.get_absolute_url())
    return render(request, 'calculadora_sellos/crear_recetas.html', context)


@login_required(login_url = '/')
def editar_receta(request, id=None):
    objeto = get_object_or_404(Receta, id=id, usuario=request.user)
    form = RecetaForm(request.POST or None, instance= objeto)
    ingredienteFormset= modelformset_factory(Ingrediente, form = IngredienteForm, extra = 0)
    qs = objeto.ingrediente_set.all()
    formset = ingredienteFormset(request.POST or None, queryset=qs)
    context = {
        "form": form,
        "formset": formset,
        "objeto": objeto
    }
    if all([form.is_valid(), formset.is_valid()]):
        parent = form.save(commit = False)
        parent.save()
        for form in formset:
            child = form.save(commit = False)
            child.receta = parent
            child.save()
        context['mensaje'] = 'Los datos han sido guardados'
    return render(request, 'calculadora_sellos/crear-editar.html', context )

def cerrar_sesion(request):
    logout(request)
    return redirect('/ingreso_usuario')

def envio_mensaje(request):
    if request.method == "POST":
        form = ContactoForm(data = request.POST)
        if form.is_valid():
            contacto = form.save(commit = False)
            contacto.save()
        return redirect('/')
    else:
        form = ContactoForm()
        return render(request,'calculadora_sellos/contacto.html', {"form":form})    
   
def eliminar_receta(request, id):
    receta = Receta.objects.get(pk=id)
    receta.delete()
    return redirect('/lista_recetas')

Servidor/calculadora_sellos/templates/calculadora_sellos/contacto.html
{% extends 'calculadora_sellos/layout.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-3">
    <h3 class="center-title">Contáctanos</h3>
    <p class="center-paragraph">Complete todos los campos del formulario. Nos pondremos en contacto lo antes posible.</p>
    <br>

<form method="POST" class="form">
    {% csrf_token %}
    <div class="form-group">
    {{form.as_p}}
    </div>
    <button class="button">Enviar</button>
</form>

{% endblock %}

Servidor/calculadora_sellos/templates/calculadora_sellos/crear-editar.html
{% extends 'calculadora_sellos/layout_usuario.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


{% if mensaje %}

<p>{{ mensaje }}</p>
{% endif %}
<div class="container">
<div style ='margin-top: 30px;'>
    <form action ="" method="POST" class="form">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-12 mb-0"><h3>Nueva Receta</h3></div>
            <div class="form-group col-md-6 mb-0">
              {{ form.nombre_receta|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.porcion|as_crispy_field }}
            </div>
          </div>

        {% if formset %}
        <h3>Ingredientes</h3>
        {{ formset.management_form|crispy }}
        <div id="ingrediente-form-list">
        {% for form in formset %}
            <div class="ingrediente-form">
                {{ form|crispy}}
                <hr style="height:5px;border:none;color:rgb(84, 142, 230);background-color:rgb(84, 142, 230);">
            </div>
        {% endfor %}
        </div>
        <div id='empty-form' class='hidden'>
            {{ formset.empty_form|crispy }}
            
        </div>
        <button style='margin-top: 20px;' id ="add-more" type="button" class="btn btn-primary">Agregar</button>

        {% endif %}
        <button style='margin-top: 20px;' type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
</div>
<script>
    const addMoreBtn = document.getElementById('add-more')
    const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
    addMoreBtn.addEventListener('click', add_new_form)

    function add_new_form(event){
        if(event){
            event.preventDefault()
        }
        const currentIngredientForms = document.getElementsByClassName('ingrediente-form')
        const currenFormCount=currentIngredientForms.length
        const formCopyTarget = document.getElementById('ingrediente-form-list')
        const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true)
        copyEmptyFormEl.setAttribute('class', 'ingrediente-form') 
        copyEmptyFormEl.setAttribute('id', `form-${currenFormCount}`) 
        const regex = new RegExp('__prefix__', 'g')
        copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currenFormCount)
        totalNewForms.setAttribute('value', currenFormCount + 1)
        
        formCopyTarget.append(copyEmptyFormEl)
    }

</script>

{% endblock %}

Servidor/calculadora_sellos/templates/calculadora_sellos/crear_recetas.html
{% extends 'calculadora_sellos/layout_usuario.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


{% if mensaje %}

<p>{{ mensaje }}</p>
{% endif %}
<div class="container">
<div style ='margin-top: 30px;'>
    <form action ="" method="POST" class="form">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-12 mb-0"><h3>Nueva Receta</h3></div>
            <div class="form-group col-md-6 mb-0">
              {{ form.nombre_receta|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{ form.porcion|as_crispy_field }}
            </div>
          </div>

        {% if formset %}
        <h3>Ingredientes</h3>
        {{ formset.management_form|crispy }}
        <div id="ingrediente-form-list">
        </div>
        <div id='empty-form' class='hidden'>
  
            {{ formset.empty_form|crispy }}
            <button class="align-self-center btn btn-danger delete-form">Borrar</button>
            
        </div>

        <button style='margin-top: 20px;' id ="add-more" type="button" class="btn btn-primary">Agregar</button>
         {% endif %}
        <button style='margin-top: 20px;' type="submit" class="btn btn-primary ">Guardar Receta</button>
    </form>
</div>
</div>
<script>
    const addMoreBtn = document.getElementById('add-more')
    const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
    addMoreBtn.addEventListener('click', add_new_form)

    function add_new_form(event){
        if(event){
            event.preventDefault()
        }
        const currentIngredientForms = document.getElementsByClassName('ingrediente-form')
        const currenFormCount=currentIngredientForms.length
        const formCopyTarget = document.getElementById('ingrediente-form-list')
        const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true)
        copyEmptyFormEl.setAttribute('class', 'ingrediente-form') 
        copyEmptyFormEl.setAttribute('id', `form-${currenFormCount}`) 
        const regex = new RegExp('__prefix__', 'g')
        copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currenFormCount)
        totalNewForms.setAttribute('value', currenFormCount + 1)
        
        formCopyTarget.append(copyEmptyFormEl)
    }
    

</script>

{% endblock %}

Servidor/calculadora_sellos/templates/calculadora_sellos/index.html
{% extends 'calculadora_sellos/layout.html' %}
{% load static %}
{% block content %}


<div class="col-sm-12">
<h3>Calculadora Nutricional</h3>

<p>En esta página encontrará una calculadora que te permitirá saber si un producto o tus recetas deben tener sellos 
nutricionales, establecidos en la Ley Nº 20.606 sobre la composición nutricional de los alimentos y su publicidad, o
“Ley de Alimentos” o "Ley de Etiquetados". Para acceder a esta, puedes registrarte <a href ="{% url 'calculadora_sellos:registro'%}">aquí</a>. Si ya tienes una cuenta, 
ingresa <a href ="{% url 'calculadora_sellos:ingreso_usuario'%}">aquí</a></p>

<p>Para el año 2022, comenzará a regir la cuerta fase, en la cual las etiquetas “ALTO EN” deberán ser implementadas
por micro productores de alimentos.</p>

<div class="col-sm-2"></div>
<div class="col-sm-8">
<h3>Límites para alimentos sólidos</h3>
<table class="center">
    <tr><th></th><th>Primera fase</th><th>Segunda fase</th><th>Tercera fase</th></tr>
    <tr><td>Calorías</td><td>350 kcal/100g</td><td>300 kcal/100g</td><td>275 kcal/100g</td></tr>
    <tr><td>Sodio</td><td>800 mg/100gg</td><td>500 mg/100g</td><td>400 mg/100g</td></tr>
    <tr><td>Azúcares</td><td>22,5 g/100g</td><td>15 g/100g</td><td>10 g/100g</td></tr>
    <tr><td>Grasas Saturadas</td><td>6 g/100g</td><td>5 g/100g</td><td>	4 g/100g</td></tr>
</table>

<h3>Límites para alimentos líquidos</h3>
<table>
    <tr><th></th><th>Primera fase</th><th>Segunda fase</th><th>Tercera fase</th></tr>
    <tr><td>Calorías</td><td>100 kcal/100ml</td><td>80 kcal/100ml</td><td>70 kcal/100ml</td></tr>
    <tr><td>Sodio</td><td>100 mg/100ml</td><td>100 mg/100ml</td><td>100 mg/100ml</td></tr>
    <tr><td>Azúcares</td><td>6 g/100ml</td><td>5 g/100ml</td><td>5 g/100ml</td></tr>
    <tr><td>Grasas Saturadas</td><td>3 g/100ml</td><td>3 g/100ml</td><td>3 g/100ml</td></tr>
</table>
</div>
<br>

<br>
</div>

{% endblock %}

Servidor/calculadora_sellos/templates/calculadora_sellos/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <title>Document</title>
</head>
<body>
    <header style="height:80px">
      <nav class="navbar navbar-fixed-top navbar-toggler">
        <div class="container-fluid">
          <div class="navbar-header">
            <img src="{% static 'img/logo.png' %}" alt="logo" class="imagenlogo">
          </div>
          
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'calculadora_sellos:index'%}">Inicio </a></li>
          <li class="active"><a href="{% url 'calculadora_sellos:recursos_externos'%}">Recursos Externos</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Ayuda<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'calculadora_sellos:sobre_pagina'%}">Sobre esta página</a></li>
              <li><a href="{% url 'calculadora_sellos:preguntas_frecuentes'%}">Preguntas Frecuentes</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'calculadora_sellos:contacto'%}">Contacto</a></li>
          <li><a href="{% url 'calculadora_sellos:registro'%}"><span class="glyphicon glyphicon-user"></span>Registrarse</a></li>
          <li><a href="{% url 'calculadora_sellos:ingreso_usuario'%}"><span class="glyphicon glyphicon-log-in"></span>Ingresar</a></li>
        </ul>
      </div>
    </nav>
    </header>

    {% block content %}
 
    {% endblock %}

<footer>
  <hr>
  <section>
      <div class="col-sm-4">
        <h6 class="fw-bold mb-4">Síguenos</h6>
        <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-google"></a>
        <a href="#" class="fa fa-linkedin"></a>
        <a href="#" class="fa fa-youtube"></a>
      </div>
    <div class="col-sm-4">
      <h6 class="fw-bold mb-4">Enlaces Externos</h6>
      <p><a href="#!" class="text-reset">Ley 20606</a></p>
      <p><a href="#!" class="text-reset">Manual de Etiquetado</a></p>
    </div>
    <div class="col-sm-4">
      <h6 class="fw-bold mb-4">Contacto</h6>
      <p>Nombre: Constanza Hurtado</p>
      <p>Correo: hurtadoavila@gamil.com</p> 
    </div>
  </section>

</footer>

</body>
</html>

Servidor/calculadora_sellos/templates/calculadora_sellos/layout_usuario.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/estilo_usuario.css' %}">
    <title>Usuario</title>
</head>
<body>
    <header>
        <div class="container">
          <div class="row row-cols-2">
            <div class="col"><h3>Bienvenid@ {{ request.user.username }}</h3></div>
            <div class="col" id ="cerrar_sesion"><a href = "/cerrar_sesion">Cerrar Sesión</a></div>
          </div>
            <br>
            <ul class="nav nav-tabs">
              <li class="active"><a href="{% url 'calculadora_sellos:lista' %}">Mis Recetas</a></li>
              <li><a href="{% url 'calculadora_sellos:crear' %}">Nueva Receta</a></li>
              <li><a href="">Guía Calculadora</a></li>
            </ul>
            <br>
            </div>
        
      </header>
    {% block content %}
 
    {% endblock %}
    <footer></footer>
</body>
</html>

Servidor/calculadora_sellos/templates/calculadora_sellos/lista_recetas.html
{% extends 'calculadora_sellos/layout_usuario.html' %}
{% load static %}
{% block content %}

<div class="container">
<h3>Lista de Recetas</h3>
<a href = "{% url 'calculadora_sellos:crear' %}">Nueva Receta</a>
<hr>
<br>
{% for objeto in lista %}
<li><a href ="{{ objeto.get_absolute_url }}"> {{ objeto.nombre_receta }}</a></li>
{% endfor %}
</div>
{% endblock %}

Servidor/calculadora_sellos/templates/calculadora_sellos/preguntas_frecuentes.html
{% extends 'calculadora_sellos/layout.html' %}
{% load static %}
{% block content %}

<main>
    <section class="container-fluid">
        <h3>Preguntas Frecuentes</h3>
        <p>Aquí encontrará respuestas rápidas sobre la Ley de etiquetado y sobre esta página. Si no encunetra lo 
            que busca en esta sección, <a href="{% url 'calculadora_sellos:contacto'%}"> contáctenos</a>. Responderemos lo antes posible.</p>
    <section class="container-fluid">
        <div class="container">
            <div class="col">
                <h5>¿Qué es este sitio?</h5>
                <p> Este sitio es una propuesta a una forma de obtener información sobre si un alimento debe
                    portar alguno de los 4 sellos conocidos como "Discos Pares" de nutrientes críticos en base a su composición. 
                    Se toma como base la Ley 20606 y el Manual de Etiquetado que ha puesto a disposición el 
                    Ministerio de Salud.</p>       
            </div>
            <hr width=800>
                <div class="col">
                    <h5>¿Qué son los nutrientes críticos?</h5>
                    <p> En el contexto de la Ley de Alimentos, corresponde a sodio, grasas saturadas o azúcares.</p>
                </div>
            <hr width=800>
            <div class="col">
                    <h5>¿Quiénes deberán agregar etiquetas de advertencia a los alimentos?</h5>
                    <p> En esta etapa se agregan a las grandes empresas, las micro y pequeñas empresas (MIPES) a la política de sellos.</p>       
            </div>
            <hr width=800>
            <div class="col">
                    <h5>¿Quiénes no deberán agregar etiquetas de advertencia a los alimentos?</h5>
                    <p> Los microproductores (microempresas) tendrán que incorporar los sellos de advertencia en 36 meses más.</p>       
            </div>
            <hr width=800>
            <div class="col">
                <h5>¿Qué considera la ley como microempresas?</h5>
                <p> Según el Estudio de Economía “Costos de implementación para Pequeñas y Micro empresas”,  Micro empresas: aquellas 
                    que, según ventas anuales y categorías definidas por ley N° 20.416, que fija normas especiales para las empresas 
                    de menor tamaño, también como “Estatuto Pyme”, tienen ventas anuales inferiores a 2.400 UF.</p>       
            </div>
            <hr width=800>
            <div class="col">
                <h5>¿Qué significan los sellos de advertencia?</h5>
                <p> La presencia de uno o más sellos de advertencia en un producto nos indica que éste presenta niveles superiores a 
                    los límites establecidos por el Ministerio de Salud, en relación a sodio, azúcares, grasas saturadas o calorías, 
                    los que se asocian a la obesidad y otras enfermedades crónicas como hipertensión, diabetes, infartos, y algunos 
                    cánceres.</p>       
            </div>
        </div>       
    </section>
</main>



{% endblock %}